version: "3.9"
services:
  ip_service:
    build: .
    image: ip-service:latest
    ports:
      - "8080:8080"
    environment:
      - MMDB_PATH=/app/data/GeoLite2-City.mmdb
    volumes:
      - ./data:/app/data:rw
    restart: unless-stopped